shadow = true;
shadow-radius = 10;
shadow-offset-x = -5;
shadow-offset-y = -5;
shadow-opacity = 1;
shadow-color = "#000000";

shadow-exclude = [
"class_g =  'Polybar'",
"class_g =  'Rofi'",
"name = 'Notification'"
]
#enable or disable animations
animations = false;

#fading
fading = true;
fade-in-step = 0.03;
fade-out-step = 0.04;
fade-delta = 10;
fade-time = 200;
fade-duration = 300;
# no-fading-openclose = true;
no-fading-destroyed-argb = true;

# blur: {
#   method = "dual_kawase";
#   strength = 5;
# }

corner-radius = 0;

# Exclude conditions for rounded corners.
# rounded-corners-exclude = [
#   "window_type = 'dock'",
#   "window_type = 'desktop'",
#   "window_type = 'dropdown_menu'"
# ];

# Exclude conditions for background blur.
# blur-background-exclude = []
# blur-background-exclude = [
#   "window_type = 'dock'",
#   "window_type = 'desktop'",
#   "window_type = 'menu'",
#   "_GTK_FRAME_EXTENTS@:c",
#   "class_g = 'Chromium'",
#   "class_g = 'Discord'",
#   "class_g = 'Dunst'",
#   "class_g = 'Peek'",
#   "class_g *?= 'slop'",
#   "class_g = 'conky'",
# ];

backend = "xrender";
vsync = true;
dithered-present = false;
detect-rounded-corners = false;
detect-client-opacity = false;
use-ewmh-active-win = true;
unredir-if-possible = false;
detect-transient = true;
glx-no-stencil = true;
use-damage = true;
xrender-sync-fence = true;
window-shader-fg = "default";
transparent-clipping = false;
log-level = "warn";

# 'WINDOW_TYPE' is one of the 15 window types defined in EWMH standard:
#     "unknown", "desktop", "dock", "toolbar", "menu", "utility",
#     "splash", "dialog", "normal", "dropdown_menu", "popup_menu",
#     "tooltip", "notification", "combo", and "dnd".


# wintypes:
# {
#   tooltip = { fade = true; shadow = false; opacity = 0.75; focus = true; full-shadow = false; };
#   dock = { shadow = false; clip-shadow-above = true; }
#   dnd = { shadow = false; }
#   popup_menu = { opacity = 0.8; }
#   dropdown_menu = { opacity = 0.8; }
# };

rules = (
{
  match = "window_type = 'tooltip' || "
          "window_type = 'popup_menu' ||"
          "window_type = 'dropdown_menu' ||"
          "window_type = 'dnd' || "
          "window_type = 'notification'";
  shadow = false;
},
{
  match = "window_type = 'tooltip' || "
          "window_type = 'popup_menu' ||"
          "window_type = 'dropdown_menu' ||"
          "window_type = 'dnd || '";
  fade = true;
  opacity = 0.8;
  full-shadow = false;
  corner-radius = 5;
},
{
  match = "window_type = 'popup_menu' || "
          "window_type = 'dropdown_menu'";
  opacity = 0.95;
},
{
  match = "window_type = 'dock'    || "
          "window_type = 'desktop' || "
          "window_type = 'menu'    || "
          "class_g = 'Polybar'";
  blur-background = false;
  shadow = false;
  corner-radius = 0;
},
{ match = "class_g = 'kitty' && focused"; opacity = 0.9; },
{ match = "class_g = 'kitty' && !focused"; opacity = 0.8; },
{ match = "class_g = 'st-256color' && focused"; opacity = 0.9; },
{ match = "class_g = 'st-256color' && !focused"; opacity = 0.8; },
{ match = "fullscreen"; opacity = 1.0; }
)
#   "90:class_g = 'kitty' && focused",
#   "75:class_g = 'kitty' && !focused",
#   "100:class_g = 'fullscreen'",
# ];


