#!/bin/env bash

# polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# autostart
pgrep -x sxhkd > /dev/null || sxhkd -c $HOME/.config/bspwm/sxhkdrc &

fcitx5 &

$HOME/.fehbg
$HOME/.config/polybar/launch.sh

picom &

bspc monitor -d 1 2 3 4 5


bspc config border_width			2
bspc config window_gap				5

bspc config split_ratio				0.52
bspc config borderless_monocle		true
bspc config gapless_monocle			true
bspc config focus_follows_pointer	true

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off

# Set rule for windows
bspc rule -a Gnome-screenshot state=floating
bspc rule -a fontforge state=floating
bspc rule -a kitty state=tiled
