#!/bin/env bash

xsetroot -cursor_name left_ptr

# polkit
/usr/lib/polkit-kde-authentication-agent-1 &

# autostart
pgrep -x sxhkd > /dev/null || sxhkd -c $HOME/.config/bspwm/sxhkdrc &

dunst &

fcitx5 &

feh --bg-scale ~/.dotfiles/walls/dock.jpg
$HOME/.fehbg
$HOME/.config/polybar/launch.sh

picom &

bspc monitor -d 1 2 3 4 5 6 7 8

bspc config border_width 1
bspc config window_gap 10

bspc config left_padding 0
bspc config right_padding 0
bspc config bottom_padding 0

bspc config focused_border_color		'#e0b06b'
bspc config normal_border_color			'#2b3338'
bspc config split_ratio					0.52
bspc config borderless_monocle			true
bspc config gapless_monocle				true
bspc config focus_follows_pointer		true

bspc desktop "^8" -l monocle

bspc rule -a Brave-browser follow=on
bspc rule -a scratchpad follow=on center=on
bspc rule -a Zathura desktop='^8' follow=on
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off

# Set rule for windows
# bspc rule -a Gnome-screenshot state=floating
# bspc rule -a fontforge state=floating
# bspc rule -a conky state=floating border=off locked=on private=on
# conky &
# Always put kitty rule at the end of file
# bspc rule -a kitty state=tiled
