[module/launcher]
type = custom/text

label = 
label-background = ${cl.ogr}
label-foreground = #ebdbb2
label-padding    = 0
label-font = 1
click-left = dunstify Hello World

##########################

[module/bspwm]
type = internal/bspwm

enable-click = true
enable-scroll = true
reverse-scroll = true
pin-workspaces = true
occupied-scroll = true


format = <label-state>
format-font = 1

label-focused = 󰮯
label-focused-padding = 1
label-focused-foreground = #20a30f

label-occupied = 󰊠
label-occupied-padding = 1
label-occupied-foreground = ${cl.fg}
label-urgent = %icon%
label-urgent-padding = 1

label-empty = 󰑊
label-empty-foreground = #615100
label-empty-padding = 1

[module/title]
type = internal/xwindow
; Available tags:
;   <label> (default)
format = <label>
format-background = ${cl.bg}
format-foreground = ${cl.fg}
format-padding = 2

; Available tokens:
;   %title%
;   %instance% (first part of the WM_CLASS atom, new in version 3.7.0)
;   %class%    (second part of the WM_CLASS atom, new in version 3.7.0)
; Default: %title%
label = %title:0:30:...%
; label = %instance%
; label-maxlen = 20

; Used instead of label when there is no window title
; Available tokens:
;   None
label-empty = Empty
label-empty-foreground = #707880

[module/tray]
type = internal/tray
format = <tray>
tray-spacing = 4pt
tray-size = 66%

[module/hide]
type = custom/script
exec = echo ""
format = <label>
format-foreground = ${cl.fg}
label = %output%
label-padding = 3pt
click-left = bash $HOME/.config/polybar/rice/scripts/togglehide.sh

[module/sep]
type = custom/text
label = " "
label-font = 1

[module/sep2]
type = custom/text
label = " "
label-padding-left = 24pt
label-font = 1

[module/arrow]
type = custom/script
exec = echo ""
format = <label>
format-foreground = ${cl.fg}
label = %output%
label-padding = 3pt

click-left = xdo raise -a "polybar-tray_eDP-1" && polybar-msg cmd toggle

[module/battery]
type = internal/battery
full-at = 99
battery = BAT0
adapter = AC
poll-interval = 5
time-format = %H:%M

format-charging = Charging <label-charging>
label-charging = "%percentage%% "
label-charging-background = ${cl.bg}
label-charging-foreground = ${cl.fg}

format-discharging = <ramp-capacity><label-discharging>
label-discharging-background = ${cl.bg}
label-discharging-foreground = ${cl.bl}
label-discharging = "%percentage%%"

format-full = <label-full>
label-full = "%percentage%%"
label-full-padding = 1
label-full-background = ${cl.bg}
label-full-foreground = ${cl.fg}

ramp-capacity-0 = 
ramp-capacity-1 = 
ramp-capacity-2 = 
ramp-capacity-3 = 
ramp-capacity-4 = 
ramp-capacity-background = ${cl.bg}
ramp-capacity-foreground = ${cl.bl}
ramp-capacity-padding = 1
ramp-capacity-font = 1

[module/mem]
type = internal/memory

interval = 3

format = <label>
format-prefix = ""
format-prefix-padding = 1
format-prefix-font = 1
format-prefix-background = ${cl.bg}
format-prefix-foreground = ${cl.gr}

label = %used%
label-background = ${cl.bg}
label-foreground = ${cl.gr}

[module/cpu]
type = internal/cpu

interval = 0.5

format = <label>
format-prefix = ""
format-prefix-padding = 1
format-prefix-font = 1
format-prefix-background = ${cl.bg}
format-prefix-foreground = ${cl.rd}

label = "%percentage%%"
label-background = ${cl.bg}
label-foreground = ${cl.rd}

[module/backlight]
type = internal/backlight

; Use the following command to list available cards:
; $ ls -1 /sys/class/backlight/
; Default: first usable card in /sys/class/backlight (new in version 3.7.0)
card = intel_backlight

; Use the `/sys/class/backlight/.../actual-brightness` file
; rather than the regular `brightness` file.
; New in version 3.6.0
; Changed in version: 3.7.0: Defaults to true also on amdgpu backlights
; Default: true
use-actual-brightness = true

; Interval in seconds after which after which the current brightness is read
; (even if no update is detected).
; Use this as a fallback if brightness updates are not registering in polybar
; (which happens if the use-actual-brightness is false).
; There is no guarantee on the precisio of this timing.
; Set to 0 to turn off
; New in version 3.7.0
; Default: 0 (5 if use-actual-brightness is false)
poll-interval = 0

; Enable changing the backlight with the scroll wheel
; NOTE: This may require additional configuration on some systems. Polybar will
; write to `/sys/class/backlight/${self.card}/brightness` which requires polybar
; to have write access to that file.
; DO NOT RUN POLYBAR AS ROOT.
; The recommended way is to add the user to the
; `video` group and give that group write-privileges for the `brightness` file.
; See the ArchWiki for more information:
; https://wiki.archlinux.org/index.php/Backlight#ACPI
; Default: false
enable-scroll = true

; Interval for changing the brightness (in percentage points).
; New in version 3.7.0
; Default: 5
scroll-interval = 10

format = <label>
format-prefix = "󰃝"
format-prefix-font = 1
format-prefix-padding = 1
format-foreground = #3c3836
format-background = ${cl.bg}
; Available tokens:
;   %percentage% (default)
label = %percentage%%

[module/audio]
type = internal/pulseaudio

; Sink to be used, if it exists (find using `pacmd list-sinks`, name field)
; If not, uses default sink
; sink = alsa_output.pci-0000_12_00.3.analog-stereo

; Use PA_VOLUME_UI_MAX (~153%) if true, or PA_VOLUME_NORM (100%) if false
; Default: true
use-ui-max = true

; Interval for volume increase/decrease (in percent points)
; Default: 5
interval = 1

; Reverses the increment/decrement on scroll event. Set this to true if you are
; using natural scrolling option on your touchpad.
; New in version 3.7.0
; Default: false
reverse-scroll = trut


; Available tags:
;   <label-volume> (default)
;   <ramp-volume>
;   <bar-volume>
format-volume = <ramp-volume><label-volume>

format-volume-foreground = ${cl.ogr}
format-volume-background = ${cl.bg}

; Available tags:
;   <label-muted> (default)
;   <ramp-volume>
;   <bar-volume>
format-muted = <label-muted>

; Available tokens:
;   %percentage% (default)
;   %decibels%
label-volume = %percentage%%

; Available tokens:
;   %percentage% (default)
;   %decibels%
label-muted = "󰝟 muted"
label-muted-foreground = #666

; Only applies if <ramp-volume> is used
ramp-volume-0 = 
ramp-volume-1 = 
ramp-volume-2 = 
ramp-volume-padding = 1

; Right and Middle click
click-right =
; click-middle =

[module/network]
type = internal/network
; Name of the network interface to display. You can get the names of the
; interfaces on your machine with `ip link`
; Wireless interfaces often start with `wl` and ethernet interface with `eno` or `eth`
interface = wlp2s0

; If no interface is specified, polybar can detect an interface of the given type.
; If multiple are found, it will prefer running interfaces and otherwise just
; use the first one found.
; Either 'wired' or 'wireless'
; New in version 3.6.0
interface-type = wireless

; Seconds to sleep between updates
; Default: 1
interval = 2

; NOTE: Experimental (might change or be removed in the future)
; Test connectivity every Nth update by pinging 8.8.8.8
; In case the ping fails 'format-packetloss' is used until the next ping
; A value of 0 disables the feature
; Default: 0
;ping-interval = 3

; @deprecated: Define min width using token specifiers (%downspeed:min% and %upspeed:min%)
; Minimum output width of upload/download rate
; Default: 3

; Accumulate values from all interfaces
; when querying for up/downspeed rate
; Default: false
accumulate-stats = true

; Consider an `UNKNOWN` interface state as up.
; Some devices like USB network adapters have
; an unknown state, even when they're running
; Default: false
unknown-as-up = true

; The unit used for displaying network speeds
; For example if set to the empty string, a speed of 5 KB/s is displayed as 5 K
; Default: B/s
; New in version 3.6.0
speed-unit =

; Available tags:
;   <label-connected> (default)
;   <ramp-signal>
format-connected = <label-connected>
format-connected-prefix = 
format-connected-prefix-font = 1
format-connected-prefix-padding = 1
format-connected-prefix-foreground = #4d4d0d
; Available tags:
;   <label-disconnected> (default)
format-disconnected = <label-disconnected>

; Used when connected, but ping fails (see ping-interval)
; Available tags:
;   <label-connected> (default)
;   <label-packetloss>
;   <animation-packetloss>
format-packetloss = <label-packetloss>

; All labels support the following tokens:
;   %ifname%    [wireless+wired]
;   %local_ip%  [wireless+wired]
;   %local_ip6% [wireless+wired]
;   %essid%     [wireless]
;   %signal%    [wireless]
;   %upspeed%   [wireless+wired]
;   %downspeed% [wireless+wired]
;   %netspeed%  [wireless+wired] (%upspeed% + %downspeed%) (New in version 3.6.0)
;   %linkspeed% [wired]
;   %mac%       [wireless+wired] (New in version 3.6.0)

; Default: %ifname% %local_ip%
label-connected = %essid%
label-connected-foreground = #4d4d0d

; Default: (none)
label-disconnected = not connected
label-disconnected-foreground = #66ffff

; Default: (none)
label-packetloss = %essid%!
label-packetloss-foreground = #fafafa

[module/date]
type = internal/date

; Seconds to sleep between updates
; Default: 1.0
interval = 1.0

; See "https://en.cppreference.com/w/cpp/io/manip/put_time" for details on how to format the date string
; NOTE: if you want to use syntax tags here you need to use %%{...}
date = %a, %d-%m-%Y%

; Optional time format
time = %H:%M

; if `date-alt` or `time-alt` is defined, clicking
; the module will toggle between formats
date-alt = %a, %d-%m-%Y%
time-alt = %H:%M:%S
; Available tags:
;   <label> (default)
format =  <label>
format-background = ${cl.bg}
format-foreground = #fff

; Available tokens:
;   %date%
;   %time%
; Default: %date%
label =  %date% 󰥔 %time%
label-font = 1

label-foreground = #282934

