#! /usr/bin/env bash

sudo cp -v /etc/pacman.d/mirrorlist /etc/pacman.d/mirrorlist.bak

sudo reflector --country cn,kr,sg,jp,tw,id --latest 10 --age 12 --fastest 10 --protocol https,http --sort rate --verbose --download-timeout 15 --save /etc/pacman.d/mirrorlist

cat /etc/pacman.d/mirrorlist

